namespace NameParser
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;

    public partial class HumanName
    {
        /// <summary>
        /// Any pieces that are not capitalized by capitalizing the first letter.
        /// </summary>
        public static readonly IDictionary<string, string> CapitalizationExceptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "ii", "II" },
            { "iii", "III" },
            { "iv", "IV" },
            { "md", "M.D." },
            { "phd", "Ph.D." }
        };

        /// <summary>
        /// Pieces that should join to their neighboring pieces, e.g. "and", "y" and "&". "of" and "the" are also include to facilitate joining multiple titles, e.g. "President of the United States".
        /// </summary>
        public static readonly ISet<string> Conjunctions = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "&", "and", "et", "e", "of", "the", "und", "y" };

        /// <summary>
        /// Name pieces that appear before a last name. They join to the piece that follows them to make one new piece.
        /// </summary>
        public static readonly ISet<string> Prefixes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "'t",
            "abu",
            "bin",
            "bon",
            "da",
            "dal",
            "de",
            "del",
            "dem",
            "den",
            "der",
            "di",
            "dí",
            "het",
            "ibn",
            "in",
            "la",
            "le",
            "onder",
            "op",
            "san",
            "santa",
            "st",
            "ste",
            "ten",
            "van",
            "vel",
            "von"
        };

        /// <summary>
        /// For handling names that start with Mc or Mac such as McBride, MacDonald
        /// </summary>
        private static readonly Regex RegexMac = new Regex(@"^(ma?c)(\w+)", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        /// <summary>
        /// For extracting optional quoted nicknames from full names.
        /// </summary>
        private static readonly Regex RegexNickname = new Regex(@"\s*(?:\((.+?)\))|(?:([""'])(.+?)\2)", RegexOptions.Compiled);

        /// <summary>
        /// Pieces that come at the end of the name but are not last names. These potentially
        /// conflict with initials that might be at the end of the name.
        /// These may be updated in the future because some of them are actually titles that just
        /// come at the end of the name, so semantically this is wrong. Positionally, it's correct.
        /// </summary>
        public static readonly ISet<string> Suffixes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "2",
            "cfp",
            "chfc",
            "clu",
            "cpa",
            "csm",
            "dds",
            "dmd",
            "do",
            "dpm",
            "esq",
            "esquire",
            "i",
            "ii",
            "iii",
            "iv",
            "jnr",
            "jr",
            "ma",
            "mba",
            "md",
            "mp",
            "phd",
            "phr",
            "pmp",
            "qc",
            "snr",
            "sr",
            "v"
        };

        ///<summary>
        /// When these titles appear with a single other name, that name is a first name, e.g.
        /// "Sir John", "Sister Mary", "Queen Elizabeth".
        /// </summary>
        public static readonly ISet<string> FirstNameTitles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "aunt",
            "auntie",
            "brother",
            "dame",
            "father",
            "king",
            "maid",
            "master",
            "mother",
            "pope",
            "queen",
            "sir",
            "sister",
            "uncle"
        };

        /// <summary>
        /// **Cannot include things that could also be first names**, e.g. "dean".
        /// Many of these from wikipedia: https://en.wikipedia.org/wiki/Title.
        /// The parser recognizes chains of these including conjunctions allowing
        /// recognition titles like "Deputy Secretary of State".
        /// </summary>
        public static readonly ISet<string> Titles = new HashSet<string>(FirstNameTitles, StringComparer.OrdinalIgnoreCase)
        {
            "1lt",
            "1sgt",
            "1stlt",
            "1stsgt",
            "2lt",
            "2ndlt",
            "a1c",
            "ab",
            "abbess",
            "abbot",
            "academic",
            "acolyte",
            "adept",
            "adjutant",
            "adm",
            "admiral",
            "advocate",
            "air",
            "akhoond",
            "alderman",
            "almoner",
            "ambassador",
            "amn",
            "analytics",
            "appellate",
            "apprentice",
            "arbitrator",
            "archbishop",
            "archdeacon",
            "archdruid",
            "archduchess",
            "archduke",
            "arhat",
            "assistant",
            "assoc",
            "associate",
            "asst",
            "attache",
            "attaché",
            "attorney",
            "ayatollah",
            "baba",
            "bailiff",
            "banner",
            "bard",
            "baron",
            "barrister",
            "bearer",
            "bench",
            "bg",
            "bgen",
            "bishop",
            "blessed",
            "bodhisattva",
            "brigadier",
            "briggen",
            "buddha",
            "burgess",
            "business",
            "bwana",
            "canon",
            "capt",
            "captain",
            "cardinal",
            "catholicos",
            "ccmsgt",
            "cdr",
            "ceo",
            "cfo",
            "chancellor",
            "chaplain",
            "chargé d'affaires",
            "chief",
            "chieftain",
            "civil",
            "clerk",
            "cmsaf",
            "cmsgt",
            "coach",
            "col",
            "colonel",
            "commander",
            "commander-in-chief",
            "commodore",
            "comptroller",
            "controller",
            "corporal",
            "corporate",
            "councillor",
            "courtier",
            "cpl",
            "cpo",
            "cpt",
            "credit",
            "criminal",
            "csm",
            "curator",
            "customs",
            "cwo-2",
            "cwo-3",
            "cwo-4",
            "cwo-5",
            "cwo2",
            "cwo3",
            "cwo4",
            "cwo5",
            "deacon",
            "delegate",
            "deputy",
            "designated",
            "dir",
            "director",
            "discovery",
            "district",
            "division",
            "docent",
            "docket",
            "doctor",
            "doyen",
            "dpty",
            "dr",
            "druid",
            "duke",
            "dutchess",
            "edmi",
            "edohen",
            "effendi",
            "ekegbian",
            "elder",
            "elerunwon",
            "emperor",
            "empress",
            "ens",
            "envoy",
            "exec",
            "executive",
            "fadm",
            "family",
            "federal",
            "field",
            "financial",
            "first",
            "flag",
            "flying",
            "foreign",
            "forester",
            "friar",
            "gen",
            "general",
            "generalissimo",
            "gentiluomo",
            "giani",
            "goodman",
            "goodwife",
            "governor",
            "grand",
            "group",
            "guru",
            "gyani",
            "gysgt",
            "hajji",
            "headman",
            "her",
            "hereditary",
            "high",
            "his",
            "hon",
            "honorable",
            "honourable",
            "imam",
            "information",
            "intelligence",
            "intendant",
            "journeyman",
            "jr",
            "judge",
            "judicial",
            "junior",
            "king's",
            "kingdom",
            "knowledge",
            "lady",
            "lama",
            "lamido",
            "law",
            "lcdr",
            "lcpl",
            "leader",
            "lieutenant",
            "lord",
            "lt",
            "ltc",
            "ltcol",
            "ltg",
            "ltgen",
            "ltjg",
            "madam",
            "madame",
            "mag",
            "mag-judge",
            "mag/judge",
            "magistrate",
            "magistrate-judge",
            "maharajah",
            "maharani",
            "mahdi",
            "maj",
            "majesty",
            "majgen",
            "manager",
            "marcher",
            "marchioness",
            "marketing",
            "marquess",
            "marquis",
            "marquise",
            "matriarch",
            "mayor",
            "mcpo",
            "mcpoc",
            "mcpon",
            "member",
            "metropolitan",
            "mg",
            "mgr",
            "mgysgt",
            "minister",
            "miss",
            "misses",
            "mister",
            "monsignor",
            "mpco-cg",
            "mr",
            "mrs",
            "ms",
            "msg",
            "msgt",
            "mufti",
            "mullah",
            "municipal",
            "murshid",
            "nanny",
            "national",
            "nurse",
            "officer",
            "operating",
            "pastor",
            "patriarch",
            "petty",
            "pfc",
            "pharaoh",
            "pilot",
            "pir",
            "po1",
            "po2",
            "po3",
            "police",
            "political",
            "prefect",
            "prelate",
            "premier",
            "pres",
            "presbyter",
            "president",
            "presiding",
            "priest",
            "priestess",
            "primate",
            "prime",
            "prin",
            "prince",
            "princess",
            "principal",
            "prior",
            "private",
            "pro",
            "prof",
            "provost",
            "pslc",
            "pursuivant",
            "pv2",
            "pvt",
            "queen's",
            "rabbi",
            "radm",
            "rangatira",
            "ranger",
            "rdml",
            "rear",
            "rebbe",
            "registrar",
            "rep",
            "representative",
            "resident",
            "rev",
            "revenue",
            "reverend",
            "right",
            "risk",
            "royal",
            "rt",
            "sa",
            "saint",
            "saoshyant",
            "scpo",
            "se",
            "secretary",
            "security",
            "seigneur",
            "senator",
            "senior",
            "senior-judge",
            "sergeant",
            "servant",
            "sfc",
            "sgm",
            "sgt",
            "sgtmaj",
            "sgtmajmc",
            "shehu",
            "sheikh",
            "sheriff",
            "siddha",
            "sma",
            "smsgt",
            "sn",
            "solicitor",
            "spc",
            "speaker",
            "special",
            "sr",
            "sra",
            "ssg",
            "ssgt",
            "staff",
            "state",
            "states",
            "strategy",
            "subaltern",
            "subedar",
            "sultan",
            "sultana",
            "superior",
            "supreme",
            "surgeon",
            "swordbearer",
            "sysselmann",
            "tax",
            "technical",
            "timi",
            "tirthankar",
            "treasurer",
            "tsar",
            "tsarina",
            "tsgt",
            "uk",
            "united",
            "us",
            "vadm",
            "vardapet",
            "vc",
            "venerable",
            "verderer",
            "vicar",
            "vice",
            "viscount",
            "vizier",
            "warden",
            "warrant",
            "wing",
            "wo-1",
            "wo1",
            "wo2",
            "wo3",
            "wo4",
            "wo5",
            "woodman",
        };
    }
}